config/routes.rb
Rails.application.routes.draw do
  root to: 'games#root'
  resources :games

  post '/draw', to: 'games#draw', as: 'draw_button'
  get '/draw', to: redirect('games#root')
  post '/shuffle', to: 'games#shuffle', as: 'shuffle_button'
  get '/shuffle', to: redirect('games#root')
  post '/show', to: 'games#show', as: 'show_button'
  get '/show', to: redirect('games#root')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord

  serialize :deck, Array
  serialize :hand, Array

  def shuffle
    new_random_deck
    self.save
  end

  # A card is drawn from the top of deck (last in array) and put in the hand.
  def draw_card
    unless self.deck.empty?
      self.hand.push(self.deck.pop)
      self.save
    end
  end

  # show: take all the cards from deck and put them in the hand
  def show
    self.deck.size.times do
      self.draw_card
    end
    self.save
  end

  def suit(card_num)
    suits = [ 'Ace', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
              'Ten', 'Jack', 'Queen', 'King' ]
    unless (card_num > 12) && (card_num < 0) then
      return suits[card_num]
    else
      return nil
    end
  end

  ###########
  private

  def card_ref
    # A unique number for each card.
    # h = hearts, c = clubs, d = diamonds, s = spades
    # 1 = ace, 2 -> 10 = number cards, 11 = jack, 12 = queen, 13 = king
    [ 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'h7', 'h8', 'h9', 'h10', 'h11', 'h12', 'h13',
      'c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10', 'c11', 'c12', 'c13',
      'd1', 'd2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8', 'd9', 'd10', 'd11', 'd12', 'd13',
      's1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12', 's13' ]
  end

  def new_random_deck
    self.hand = []
    self.deck = self.card_ref.shuffle
    self.save
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    render :template => 'games/root'
  end

  def draw
    @game = Game.find(session[:game_id])
    prev_size = @game.hand.size
    @game.draw_card
    if @game.hand.size > prev_size then
      redirect_to games_url, notice: "You have drawn a card."
    else
      redirect_to games_url, notice: "You did NOT draw a card."
    end
  end

  def shuffle
    Game.find(session[:game_id]).shuffle
    redirect_to games_url, notice: "You have re-shuffled the deck."
  end

  def show
    Game.find(session[:game_id]).show
    redirect_to games_url, notice: "You have drawn all cards from the deck!"
  end

  def new
    @game = Game.new
    @game.shuffle
    session[:game_id] = @game.id
    redirect_to games_url, notice: "You have created a new game."
  end

  def update
    @game = Game.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/root.html.erb
  <body>
    <p id="notice" style='font-size: 150%'><%= notice %></p>
    <!-- <p>--- session:</p> -->
    <%#= raw session.inspect %>

    <% if session[:game_id].blank? then %>
      <h2>Your game was not found.</h2>
      <%= link_to 'New', new_game_path %>
    <% else %>

      <% @game = Game.find(session[:game_id]) %>

      <!-- <p>--- @game:</p> -->
      <%#= @game.inspect %>

      <hr>
      <%= button_to 'Draw', draw_button_path %>
      <%= button_to 'Shuffle', shuffle_button_path %>
      <%= button_to 'Show', show_button_path %> </p>
      <h2>Your Hand:</h2>
      </br>
      <% if @game.hand.size > 0 then %>
        <h3>Hearts:</h3>
        <% @game.hand.each do |card| %>
          <%= if card =~ /^h(\d+)$/ then raw "#{@game.suit($1.to_i)} " end %>
        <% end %>
        <h3>Clubs:</h3>
        <% @game.hand.each do |card| %>
          <%= if card =~ /^c(\d+)$/ then raw "#{@game.suit($1.to_i)} " end %>
        <% end %>
        <h3>Diamonds:</h3>
        <% @game.hand.each do |card| %>
          <%= if card =~ /^d(\d+)$/ then raw "#{@game.suit($1.to_i)} " end %>
        <% end %>
        <h3>Spades:</h3>
        <% @game.hand.each do |card| %>
          <%= if card =~ /^s(\d+)$/ then raw "#{@game.suit($1.to_i)} " end %>
        <% end %>
      <% else %>
        <p>No cards yet in your hand.</p>
      <% end %>
    <% end %>

  </body>

</html>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Deck:</h2>
<%= @game.deck %>
<h2>Hand:</h2>
<%= @game.hand %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cardgame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>